### ISSUE TITLE
 Unable to find a specification for `Sentry (= 7.5.0)` depended upon by `ComplyCubeMobileSDK`

### ISSUE THREAD

**Issue by UserNoAvailable** [complycube/complycube-flutter-sdk#2]
[!] Unable to find a specification for `Sentry (= 7.5.0)` depended upon by `ComplyCubeMobileSDK`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I was finish config iOS step 1,2 and flutter step 1,2,3 when I run pod install I got this error, any solution idea for this bug?

I used: 
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (8 weeks ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2

Cocoapods version: 1.14.3

**Comment by ccnasro** [comment]
This issue is resolved within version 0.0.9
