### ISSUE TITLE
JFrog repository token

### ISSUE THREAD

**Issue by lslnice** [complycube/complycube-flutter-sdk#3]
How do I get the JFrog repository token?

**Comment by ccnasro** [comment]
Hello, 

Please [contact sales](https://www.complycube.com/en/contact/contact-sales/) to have access to the SDK's repository, 

Once you have credentials to your repo, you can get your pub token by clicking on "Set me up" on [this page](https://complycuberepo.jfrog.io/ui/repos/tree/General/cc-pub-release-local), iOS token from [here](https://complycuberepo.jfrog.io/ui/repos/tree/General/cc-cocoapods-release-local), Android from [here](https://complycuberepo.jfrog.io/ui/repos/tree/General/cc-gradle-release-local).
